n = int(input('Digite um numero para saber sua tabuada: '))
n2 = (n*2)
n3 = (n*3)
n4 = (n*4)
n5 = (n*5)
n6 = (n*6)
n7 = (n*7)
n8 = (n*8)
n9 = (n*9)
n0 = (n*10)
print('---------------------')
print(' {} x 1 = {} \n {} x 2 = {} \n {} x 3 = {} \n {} x 4 = {} \n {} x 5 = {}'.format(n, n, n, n2, n, n3, n, n4, n, n5))
print(' {} x 6 = {} \n {} x 7 = {} \n {} x 8 = {} \n {} x 9 = {} \n {} x 10 = {}'.format(n, n6, n, n7, n, n8, n, n9, n, n0))
print('---------------------')
